name: gwe
version: 0.12.3
summary: System uility.
description: A system utility designed to provide information, control the fans and overclock your NVIDIA card.


grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

plugs:
  gnome-3-32-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-32-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
  magic:
    plugin: nil
    build-environment: &buildenv
      - PATH: $PATH:$SNAPCRAFT_STAGE/usr/bin
      - XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAPCRAFT_STAGE/usr/share:/usr/share
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/pkgconfig-build
      - ACLOCAL_PATH: $SNAPCRAFT_STAGE/usr/share/aclocal
      - GI_TYPELIB_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      - VAPIDIR: $SNAPCRAFT_STAGE/usr/share/vala/vapi:$SNAPCRAFT_STAGE/usr/share/vala-0.40/vapi:$SNAPCRAFT_STAGE/usr/share/vala-0.36/vapi:$SNAPCRAFT_STAGE/usr/share/vala-0.30/vapi
      - VALAFLAGS: " --vapidir $SNAPCRAFT_STAGE/usr/share/vala/vapi $SNAPCRAFT_STAGE/usr/share/vala-0.40/vapi $SNAPCRAFT_STAGE/usr/share/vala-0.36/vapi $SNAPCRAFT_STAGE/usr/share/vala-0.30/vapi"
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAPCRAFT_STAGE/usr/lib/vala-0.40
      - CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH:$SNAPCRAFT_STAGE
      - CMAKE_INCLUDE_PATH: $CMAKE_INCLUDE_PATH:$SNAPCRAFT_STAGE/include:$SNAPCRAFT_STAGE/usr/include
      - CMAKE_LIBRARY_PATH: $CMAKE_LIBRARY_PATH:$SNAPCRAFT_STAGE/lib:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

apps:
  gwe:
    command: gwe
    plugs:
      - home
      - network
      - removable-media
      - opengl

parts:
 gwe:
    plugin: python
    python-version: python3
    source: https://gitlab.com/leinardi/gwe.git
    source-type: git
    override-pull: |
      git clone https://gitlab.com/leinardi/gwe.git src/gitlab.com/leinardi/gwe
       cd src/gitlab.com/leinardi/gwe
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
    build-packages:
      - git
      - sed
    stage-packages:
      - python-six 
      
      
      gobject-introspection:
    after: [glib, cairo]
    source: https://gitlab.gnome.org/GNOME/gobject-introspection.git
    #source-branch: gnome-3-28
    plugin: autotools
    configflags: [ --prefix=/usr, --with-python=python3 ]
    build-environment: *buildenv
    override-build: |
      set -eux
      snapcraftctl build
      SCANNER=$SNAPCRAFT_PART_INSTALL/usr/bin/g-ir-scanner
      mkdir -p $SNAPCRAFT_STAGE/usr/bin
      cp $SCANNER $SNAPCRAFT_STAGE/usr/bin/g-ir-scanner.orig
      sed -i 's#/usr/lib#$SNAPCRAFT_STAGE/usr/lib#' $SCANNER
      sed -i 's#/usr/share#$SNAPCRAFT_STAGE/usr/share#' $SCANNER
      PKGCONFIG_BUILD=$SNAPCRAFT_STAGE/pkgconfig-build
      mkdir -p $PKGCONFIG_BUILD
      PC=gobject-introspection-1.0.pc
      SRC=$SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig/$PC
      DST=$PKGCONFIG_BUILD/$PC
      cp $SRC $DST
      sed -i 's#^prefix=#prefix=$SNAPCRAFT_STAGE#' $DST
    build-packages:
      - python3-dev
      - libffi-dev
      - python3-mako
      - bison
      - flex
     
  glib:
    source: https://gitlab.gnome.org/GNOME/glib.git
    source-branch: glib-2-58
    configflags: [ --prefix=/usr ]
    plugin: autotools
    build-environment: *buildenv
    override-build: |
      set -eux
      snapcraftctl build
      PKGCONFIG_BUILD=$SNAPCRAFT_STAGE/pkgconfig-build
      mkdir -p $PKGCONFIG_BUILD
      PC=glib-2.0.pc
      SRC=$SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig/$PC
      DST=$PKGCONFIG_BUILD/$PC
      cp $SRC $DST
      sed -i 's#libdir=#libdir=$SNAPCRAFT_STAGE#' $DST
      sed -i 's#includedir=#includedir=$SNAPCRAFT_STAGE#' $DST
    build-packages:
      - automake
      - autoconf
      - autotools-dev
      - libtool
      - libmount-dev

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
